### ISSUE TITLE
Implement a default inventory for simple use cases.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/dash#22]
In order to lower the barrier, Dash should be able to run against an embedded default inventory such that simple repositories with a predictable directory structure could run without its own inventory file.
(see below for proposed default values)

```
verison: 3.0
resource_groups:
  - name: Default Resources
    resources:
    - name: Raw Manifests
      file: manifests/
    - name: Helm Templates
      template: helm/
      type: helm
    - name: OpenShift Templates
      template: openshift-templates/
      params: openshift-template-params/
```
